SELECT * FROM boutique.category;

INSERT INTO boutique.category (ID, NAME , DESCRIPTION, CREATED_DATE,  LAST_MODIFIED_DATE) VALUES (1,'Serwel Slim', 'Serwel Celio Coupe Slim', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO boutique.category (ID, NAME , DESCRIPTION, CREATED_DATE,  LAST_MODIFIED_DATE) VALUES (2,'Serwel Straight', 'Serwel Celio Coupe Straight', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO boutique.category (ID, NAME , DESCRIPTION, CREATED_DATE,  LAST_MODIFIED_DATE) VALUES (3,'Serwel Regular', 'Serwel Celio Coupe Regular', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);